name: Format Python

on:
  push:
    paths: &py_paths
      - "**/*.py"
      - "**/poetry.lock"
      - "**/uv.lock"
      - "**/pyproject.toml"
      - "src/zxcv/**"
      - ".github/workflows/lint-py.yaml"
  pull_request:
    paths: *py_paths

jobs:
  run-root-linter:
    name: Lint (root via Poetry)
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pipx install poetry
      - name: Ensure venv uses runner Python
        run: poetry env use python
      - name: Cache Poetry venv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: poetry-venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: poetry-venv-${{ runner.os }}-
      - name: Install dependencies (root)
        run: poetry install --no-interaction --no-root
      - name: Lint (root)
        run: |
          poetry run ruff check . --fix
          poetry run ruff format .
  run-zxcv-linter:
    name: Lint (src/zxcv via uv)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/zxcv
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: pipx install uv
      - name: Cache uv and venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            src/zxcv/.venv
          key: uv-venv-${{ runner.os }}-${{ hashFiles('src/zxcv/uv.lock', 'src/zxcv/pyproject.toml') }}
          restore-keys: uv-venv-${{ runner.os }}-
      - name: Sync dependencies (zxcv)
        run: |
          if [ -f uv.lock ]; then
            uv sync --frozen
          else
            uv sync
          fi
      - name: Lint (zxcv)
        run: |
          uv run ruff check . --fix
          uv run ruff format .
